version: '3.8'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "7869:7869"
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7869", "--reload"]
